main.cpp File Reference
main.cpp File Reference
Entry point for various projects, managing initialization and main loop operations.
#include "Examples/UserConfiguration.h"
#include "../lib/ProtoTracer/ExternalDevices/InputDevices/ButtonHandler.h"
#include "Examples/Protogen/ProtogenHUB75Project.h"
#include "../lib/ProtoTracer/Controller/HUB75Controller.h"
#include "Utils/Bluetooth.hpp"
#include <EEPROM.h>
#include <SparkFun_APDS9960.h>
#include <Wire.h>
#include "../lib/ProtoTracer/ExternalDevices/InputDevices/Menu/Menu.h"
Functions
void setup ()
Arduino setup function, initializes the selected project.
void loop ()
Arduino main loop function, animates, renders, and updates the selected project.
Variables
DanulalProto::Utils::BluetoothController bluetooth
Menu menu
SparkFun_APDS9960 boopSensor = SparkFun_APDS9960()
uint8_t proximity_data = 0
bool booped = false
RGBColor color
RGBColor BTcolor
Detailed Description
Entry point for various projects, managing initialization and main loop operations.
This file determines which project to run based on the defined preprocessor directive and provides functionality for initializing and executing the selected project.
Supported projects:
PROJECT_PROTOGEN_HUB75
PROJECT_PROTOGEN_WS35
PROJECT_PROTOGEN_BETA
PROJECT_VERIFY_ENGINE
PROJECT_VERIFY_HARDWARE
22/12/2024 22/12/2024
Version
1.0 Coela Can't! Coela Can't
Definition in file main.cpp.
Function Documentation
loop()
void loop ()
Arduino main loop function, animates, renders, and updates the selected project.
If PROJECT_VERIFY_HARDWARE is defined, this function is disabled.
< Calculates animation ratio based on time.
< Animates the project based on the current ratio.
< Renders the project's scene.
< Displays the rendered frame.
< Outputs debugging and performance statistics.
Definition at line 135 of file main.cpp.
References RGBColor::B, bluetooth, booped, boopSensor, BTcolor, color, RGBColor::G, BluetoothController::getColor(), BluetoothController::getExpression(), BluetoothController::getExpressionOverride(), BluetoothController::getGayMode(), BluetoothController::getMenuButton(), BluetoothController::getMenuOverride(), menu, proximity_data, RGBColor::R, BluetoothController::run(), and Menu::UseBoopSensor().
setup()
void setup ()
Arduino setup function, initializes the selected project.
If PROJECT_VERIFY_HARDWARE is defined, runs continuous hardware testing.
< Initializes the serial port for debugging.
< Initializes the selected project.
< Ensures stability after initialization.
Definition at line 90 of file main.cpp.
References RGBColor::B, boopSensor, color, RGBColor::G, RGBColor::R, HardwareTest::ScanDevices(), HardwareTest::TestBoopSensor(), HardwareTest::TestHUD(), and HardwareTest::TestNeoTrellis().
Variable Documentation
bluetooth
DanulalProto::Utils::BluetoothController bluetooth
Definition at line 59 of file main.cpp.
Referenced by loop().
booped
bool booped = false
Definition at line 66 of file main.cpp.
Referenced by loop().
boopSensor
SparkFun_APDS9960 boopSensor = SparkFun_APDS9960()
Definition at line 64 of file main.cpp.
Referenced by loop(), setup(), and SerialSync::SetUseBoopSensor().
BTcolor
RGBColor BTcolor
Definition at line 69 of file main.cpp.
Referenced by loop().
color
RGBColor color
Definition at line 68 of file main.cpp.
Referenced by ProtogenProject::AddBackgroundMaterialFrame(), ProtogenProject::AddMaterialFrame(), HeadsUpDisplay::ApplyEffect(), Rasterizer::CheckRasterPixel(), Rasterizer::CheckRasterPixelAccel(), ProtogenHUB75Project::CustomFaceColor(), Triangle3D::DidIntersect(), DisplayTest::FillAltWhiteBlack(), DisplayTest::FillWhite(), loop(), Rasterizer::Rasterize(), ProtogenProject::SetCustomColor(), SerialSync::SetFaceColor(), FlowNoise::SetGradient(), and setup().
menu
Menu menu
Definition at line 62 of file main.cpp.
Referenced by HeadsUpDisplay::CheckInvertPrintText(), and loop().
proximity_data
uint8_t proximity_data = 0
Definition at line 65 of file main.cpp.
Referenced by loop().